[context.production]
  command = "npm run build"

[context.production.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "https://mijnmacmekkert.nl"

[context.development]
  command = "npm run ntl-dev"

[context.development.environment]
  NODE_ENV = "development"
  VITE_BASE_URL = "https://development.mijnmacmekkert.nl"
