[context.production]
  command = "npm run build:prod"

[context.production.environment]
  NODE_ENV = "development"
  VITE_BASE_URL = "https://inspirebreda.nl/"

[context.development]
  command = "npm run build"

[context.development.environment]
  NODE_ENV = "development"
  VITE_BASE_URL = "https://development.inspirebreda.nl/"
